// <auto-generated />
using System;
using ApiTCC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiTCC.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260815002432_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiTCC.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CpfPetwalker")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nchar(11)")
                        .IsFixedLength();

                    b.Property<DateTime>("DataPublicacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.Property<string>("Rga")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nchar(7)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("CpfPetwalker");

                    b.HasIndex("Rga");

                    b.ToTable("TB_AVALIACOES", (string)null);
                });

            modelBuilder.Entity("ApiTCC.Models.LocalizacaoPasseio", b =>
                {
                    b.Property<int>("IdPasseio")
                        .HasColumnType("int");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)")
                        .IsFixedLength();

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdPasseio");

                    b.ToTable("TB_LOCALIZACAO_PASSEIO", (string)null);
                });

            modelBuilder.Entity("ApiTCC.Models.Passeio", b =>
                {
                    b.Property<int>("IdPasseio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPasseio"));

                    b.Property<string>("CpfPetwalker")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nchar(11)")
                        .IsFixedLength();

                    b.Property<DateTime>("DataPass")
                        .HasColumnType("date");

                    b.Property<int>("Duracao")
                        .HasColumnType("int");

                    b.Property<string>("Rga")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nchar(7)")
                        .IsFixedLength();

                    b.Property<string>("StatusPass")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("IdPasseio");

                    b.HasIndex("CpfPetwalker");

                    b.HasIndex("Rga");

                    b.ToTable("TB_PASSEIOS", (string)null);
                });

            modelBuilder.Entity("ApiTCC.Models.Pet", b =>
                {
                    b.Property<string>("Rga")
                        .HasMaxLength(7)
                        .HasColumnType("nchar(7)")
                        .IsFixedLength();

                    b.Property<string>("CpfDono")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nchar(11)")
                        .IsFixedLength();

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Foto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<string>("Porte")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Rga");

                    b.HasIndex("CpfDono");

                    b.ToTable("TB_PETS", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pet_Porte", "Porte IN ('Grande','Medio','Pequeno')");

                            t.HasCheckConstraint("CK_Pet_Sexo", "Sexo IN ('Macho','Femea')");
                        });
                });

            modelBuilder.Entity("ApiTCC.Models.PetwalkerPerfil", b =>
                {
                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("nchar(11)")
                        .IsFixedLength();

                    b.Property<string>("AreaAtendimento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Disponibilidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Cpf");

                    b.ToTable("TB_PETWALKER_PERFIL", (string)null);
                });

            modelBuilder.Entity("ApiTCC.Models.Transacao", b =>
                {
                    b.Property<int>("IdTransacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTransacao"));

                    b.Property<DateOnly>("DataPgmt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdPasseio")
                        .HasColumnType("int");

                    b.Property<string>("MtdPgmt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusPgmt")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdTransacao");

                    b.HasIndex("IdPasseio");

                    b.ToTable("TB_TRANSACOES", (string)null);
                });

            modelBuilder.Entity("ApiTCC.Models.Usuario", b =>
                {
                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("nchar(11)")
                        .IsFixedLength();

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)")
                        .IsFixedLength();

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Foto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Nao informado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StatusUser")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UltimoLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Cpf");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("TB_USUARIOS", null, t =>
                        {
                            t.HasCheckConstraint("CK_Usuario_StatusUser", "StatusUser IN ('Disponivel','Ausente','Nao Perturbar','Invisivel')");

                            t.HasCheckConstraint("CK_Usuario_TipoUsuario", "TipoUsuario IN ('Dono','Petwalker','Ambos')");
                        });
                });

            modelBuilder.Entity("ApiTCC.Models.Avaliacao", b =>
                {
                    b.HasOne("ApiTCC.Models.PetwalkerPerfil", "PetwalkerPerfil")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("CpfPetwalker")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiTCC.Models.Pet", "Pet")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("Rga")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("PetwalkerPerfil");
                });

            modelBuilder.Entity("ApiTCC.Models.LocalizacaoPasseio", b =>
                {
                    b.HasOne("ApiTCC.Models.Passeio", "Passeio")
                        .WithOne("LocalizacaoPasseio")
                        .HasForeignKey("ApiTCC.Models.LocalizacaoPasseio", "IdPasseio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Passeio");
                });

            modelBuilder.Entity("ApiTCC.Models.Passeio", b =>
                {
                    b.HasOne("ApiTCC.Models.PetwalkerPerfil", "PetwalkerPerfil")
                        .WithMany("Passeios")
                        .HasForeignKey("CpfPetwalker")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiTCC.Models.Pet", "Pet")
                        .WithMany("Passeios")
                        .HasForeignKey("Rga")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("PetwalkerPerfil");
                });

            modelBuilder.Entity("ApiTCC.Models.Pet", b =>
                {
                    b.HasOne("ApiTCC.Models.Usuario", "Dono")
                        .WithMany("Pets")
                        .HasForeignKey("CpfDono")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dono");
                });

            modelBuilder.Entity("ApiTCC.Models.PetwalkerPerfil", b =>
                {
                    b.HasOne("ApiTCC.Models.Usuario", "Usuario")
                        .WithOne("PetwalkerPerfil")
                        .HasForeignKey("ApiTCC.Models.PetwalkerPerfil", "Cpf")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiTCC.Models.Transacao", b =>
                {
                    b.HasOne("ApiTCC.Models.Passeio", "Passeio")
                        .WithMany("Transacoes")
                        .HasForeignKey("IdPasseio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Passeio");
                });

            modelBuilder.Entity("ApiTCC.Models.Passeio", b =>
                {
                    b.Navigation("LocalizacaoPasseio")
                        .IsRequired();

                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("ApiTCC.Models.Pet", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Passeios");
                });

            modelBuilder.Entity("ApiTCC.Models.PetwalkerPerfil", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Passeios");
                });

            modelBuilder.Entity("ApiTCC.Models.Usuario", b =>
                {
                    b.Navigation("Pets");

                    b.Navigation("PetwalkerPerfil");
                });
#pragma warning restore 612, 618
        }
    }
}
